#!/bin/bash
# Running in bash

# Christian Tonnesen
# 260847409

Argument=$1
Owner=$2

# Defines the positional parameters as variables

if [ "$#" -ne 2 ]; then
	echo "Error: Wrong number of arguments. Please type ./mkproj ARGUMENT OWNER. The argument is the name of the project. The OWNER is the user name the project belongs to."
	exit 1
fi

# Ensure the right number of arguments are there

cd ~

if [ ! -d "Projects" ]; then
	mkdir -p  Projects
fi

# Make directories if not already present

cd ~/Projects

if [ -d $Argument ]; then 
	echo "Error: The project name has already been used. Please select another project name and try again."
	cd ..
	exit 1
else
	mkdir -p $Argument
fi

# In the event the directory exists, then give an error and exit. otherwise, make the directory

cd $Argument

mkdir backup docs assets database source

ls

# Creates the subdirectories and shows them to the user

cd docs 

echo "Created by: $Owner" > "readme.txt"

cat readme.txt

# Creates a text file and shows the content to the user
